name: get-azure-env-vars-action
description: 'Action to get secrets from Azure Key Vault'
author: Braydon Harris
inputs:
  keyvault_name: 
    description: 'Name of the Azure Key Vault'
    required: true
  app_name: 
    description: 'Name of the app to get'
    required: true
  env: 
    description: 'Environment to get secrets for'
    required: true
outputs:
  secrets:
    description: 'Secret names that were retrieved'
branding:
  icon: 'code'
  color: 'red'
runs:
  using: 'node20'
  main: 'dist/index.js'