# This is a basic workflow that is manually triggered

name: Publish to Github releases

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        tags:
            - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Initial Setup
              run: |
                  npm ci
                  npm run build

            - name: 'Create zip'
              run: |
                  cp action.yml dist/
                  zip -r dist.zip dist

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                    Publish new version
                draft: true
                prerelease: false

            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist.zip
                asset_name: dist.zip
                asset_content_type: application/zip

            - name: Publish release
              uses: StuYarrow/publish-release@v1.1.2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                id: ${{ steps.create_release.outputs.id }}
